In [1]:
import numpy as np

In [3]:
twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [10]:
newTwoDArray = np.insert(twoDArray, 2, [[1,2,3,4]], axis=0)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [ 1  2  3  4]
 [12 17 12  8]
 [15 18 14  9]]


In [16]:
print(len(newTwoDArray))

5


In [15]:
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [17]:
print(len(newTwoDArray))

5


In [18]:
print(len(newTwoDArray[0]))

4


In [19]:
def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('Incorrect Index')
    else:
        print(array[rowIndex][colIndex])

In [23]:
#memanggil nilai elementnya
accessElements(newTwoDArray, 1,2)

11


In [24]:
def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

In [26]:
traverseTDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [27]:
def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located index '+str(i)+" "+str(j)
    return 'The element no found'
        

In [29]:
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [32]:
print(searchTDArray(twoDArray, 11))

The value is located index 0 0


In [38]:
newTDArray = np.delete(twoDArray, 2, axis=0)
print(newTDArray)

[[11 15 10  6]
 [10 14 11  5]
 [15 18 14  9]]


In [39]:
shoppingList = ['Milk', 'Cheese', 'Butter']

In [40]:
for i in range(len(shoppingList)):
        shoppingList[i] = shoppingList[i]+"+"
        print(shoppingList[i])
empty = []
for i in empty:
    print("I am empty")

Milk+
Cheese+
Butter+


In [41]:
myList = [1,2,3,4,5,6,7]
print(myList)

[1, 2, 3, 4, 5, 6, 7]


In [42]:
myList.insert(4,15)

myList.append(55)

newList = [11,12,13,14]
myList.extend(newList)
print(myList)

[1, 2, 3, 4, 15, 5, 6, 7, 55, 11, 12, 13, 14]


In [43]:
myList = [10,20,30,40,50,60,70,80,90]

def searchinList(list, value):
    for i in list:
        if i == value:
            return list.index(value)
    return 'The value does not exist in the list'

print(searchinList(myList, 100))

The value does not exist in the list


In [45]:
total = 0
count = 0
while (True):
    inp = input('Enter a number: ')
    if inp == 'done': break
    value = float(inp)
    total = total + value
    count = count + 1
    average = total / count
print('Average:',average)

Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: 7
Enter a number: done
Average: 7.0
